### PR TITLE
support forward declarations of extern types

### LINKED ISSUE #20: Doesn't work with VST SDK 3.8.0
VST SDK 3.8.0 added forward-declared external C structs for the first time (for wayland support),

now this crate fails with errors like:

```
error[E0412]: cannot find type `xdg_toplevel` in this scope
    --> /Users/russruss/proj/sdks/vst3-rs/target/debug/build/vst3-df5410d317aec359/out/bindings.rs:1378:23
     |
1378 |             ) -> *mut xdg_toplevel
     |                       ^^^^^^^^^^^^ not found in this scope
```

This is because `xdg_toplevel` isn't defined so we don't parse the record definition.

### PR DESCRIPTION
**Pull request by russellmcc**
This is used in the 3.8.0 sdk for wayland support. Fixes #20

### CODE REVIEW

**Comment by micahrj** [comment]
Looks good, thanks for implementing this!

It looks like this approach will generate duplicate definitions when there are multiple forward declarations of a type with no definition, but I think fixing that can be left to future work since it's not currently an issue.
